import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="tr">
      <body className={inter.className}>
        <div className="px-3 lg-px-16">
          <nav className="rounded-2xl navbar text-primary-content bg-primary shadow-2xl mt-6">
            <div className="flex-1">
              <Link className="btn btn-ghost text-xl" href={'/'}>
                B&R Elektronik
              </Link>
            </div>
            <div className="flex-none">
              <ul className="menu menu-horizontal">
                <li>
                  <Link href={'/koltest'}>Kol Test</Link>
                </li>
                <li>
                  <details>
                    <summary>Katalog</summary>
                    <ul className=" bg-primary rounded-t-none z-10 shadow-lg !mt-0">
                      <li>
                        <Link href={'/oyunlar'}>Oyunlar</Link>
                      </li>
                      <li>
                        <a>Konsollar</a>
                      </li>
                    </ul>
                  </details>
                </li>
              </ul>
            </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
  )
}
